version: '2'
services:
  app_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: npm run test:ci
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    links:
      - db_test
    depends_on:
      - db_test
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      NODE_ENV: test
  db_test:
    image: postgres
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
