version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: npm run test:ci
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    links:
      - db
    depends_on:
      - db
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  db:
    image: postgres
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
