stack: ppeerttu/chat-app
version: 1.0.0
description: Chat app testing environment

variables:
  app_version:
    type: string
    from:
      vault: APP_VERSION
  front_version:
      type: string
      from:
        vault: FRONT_VERSION

services:
  web:
    image: "ppeerttu/chat-app-front:${front_version}"
    stateful: true
    environment:
      - KONTENA_LB_MODE=http
      - KONTENA_LB_VIRTUAL_PATH=/
      - KONTENA_LB_INTERNAL_PORT=80
      - KONTENA_LB_KEEP_VIRTUAL_PATH=true
      - KONTENA_LB_CUSTOM_SETTINGS=redirect scheme https code 301 if !{ ssl_fc }
    secrets:
      - secret: APP_DOMAIN
        name: KONTENA_LB_VIRTUAL_HOSTS
        type: env
    links:
      - lb-internet/lb-public

  app:
    image: "ppeerttu/chat-app-back:${app_version}"
    stateful: true
    environment:
      - KONTENA_LB_MODE=http
      - KONTENA_LB_INTERNAL_PORT=3000
      - KONTENA_LB_VIRTUAL_PATH=/api
      - KONTENA_LB_KEEP_VIRTUAL_PATH=true
      - KONTENA_LB_CUSTOM_SETTINGS=redirect scheme https code 301 if !{ ssl_fc }
      - NODE_ENV=production
    links:
      - lb-internet/lb-public
    depends_on:
      - db
    secrets:
      - secret: APP_DOMAIN
        name: KONTENA_LB_VIRTUAL_HOSTS
        type: env
      - secret: POSTGRES_USER
        name: POSTGRES_USER
        type: env
      - secret: POSTGRES_PASSWORD
        name: POSTGRES_PASSWORD
        type: env
      - secret: POSTGRES_DB
        name: POSTGRES_DB
        type: env

  db:
    image: postgres:9.6.2
    stateful: true
    volumes:
      - db_volume:/var/lib/postgresql/data
    secrets:
      - secret: POSTGRES_USER
        name: POSTGRES_USER
        type: env
      - secret: POSTGRES_PASSWORD
        name: POSTGRES_PASSWORD
        type: env
      - secret: POSTGRES_DB
        name: POSTGRES_DB
        type: env

volumes:
  db_volume:
    external:
      name: db-volume
